version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"

    # Open a new pull request every month, if there are updates available.
    schedule:
      interval: "monthly"
      timezone: "Europe/Berlin"

    labels:
      - "enhancement"

    # Create one pull request for all dependencies.
    groups:
      all:
        patterns:
          - "*"
