name: Remove Experimental Packages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  remove-experimental:
    uses: ronin-co/actions/.github/workflows/remove-experimental.yml@main
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_TOKEN_READ_AND_WRITE: ${{ secrets.NPM_TOKEN_READ_AND_WRITE }}