name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ronin-co/actions/.github/workflows/validate.yml@main
    with:
      upload_coverage: true
    secrets:
      ORG_CODECOV_TOKEN: ${{ secrets.ORG_CODECOV_TOKEN }}